version: "3"
services:
  react-app:
    build: ./frontend
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - ern-app
  api-server:
    build: ./backend
    ports:
      - "4000:4000"
    networks:
      - ern-app
networks:
  ern-app:
    driver: bridge